services:
  # Unified service for frontend and backend
  - type: web
    name: userstory-ui
    env: python
    buildCommand: |
      # Install Node.js dependencies and build frontend
      npm install
      npm run build
      # Install Python dependencies for backend
      cd backend
      pip install --upgrade pip
      pip install --prefer-binary -r requirements.txt
    startCommand: |
      cd backend
      python main.py
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: OPENAI_API_KEY
        sync: false  # You'll need to set this manually in Render dashboard