services:
  # Frontend service
  - type: web
    name: userstory-ui-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  # Backend service  
  - type: web
    name: userstory-ui-backend
    env: python
    rootDir: backend
    buildCommand: |
      export CARGO_HOME=/tmp/cargo
      export CARGO_TARGET_DIR=/tmp/cargo-target
      mkdir -p /tmp/cargo /tmp/cargo-target
      pip install --upgrade pip
      pip install --prefer-binary -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: OPENAI_API_KEY
        sync: false  # You'll need to set this manually in Render dashboard
